title: 我的博客
description: 记录与分享
theme: minima   # GitHub Pages 原生主题，省心
paginate: 10
sidebar:
  name: 洲楚
  title: 记录者 · 学习者
  bio: 你好！我会在这里分享学习与生活中的灵感与成长故事
  avatar: /assets/images/avatar.jpg
  links:
    - title: GitHub
      url: https://github.com/lywhlao2025
      new_tab: true
    - title: 邮箱
      url: mailto:lywhlao@163.com
